### ISSUE TITLE
Using the generated artwork

### ISSUE THREAD

**Issue by ghost** [tomkinsc/carcassonne-shading#1]
Hi @tomkinsc, first let me say you and your partner did a fantastic job putting this together, tracing the tiles, etc. 

I would like to use the generated SVG tiles to create an open source computer version of game, mostly for self-study as I am learning a new programming language.

**Comment by tomkinsc** [comment]
Hi @bucaran, thanks for asking. I've added an [Attribution-NonCommercial-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-nc-sa/4.0/) to this project. You may use the artwork, as long as the use is non-commercial (we don't want to take revenue away from the original creators of the Carcassonne board game). Please include a link somewhere to this repository if you end up posting the code publicly.

**Comment by ghost** [comment]
Of course. Thanks.
